### ISSUE TITLE
Update version of apollo-server-express

### ISSUE THREAD

**Issue by rodebert** [spring-media/themis-graphql#44]
After a fresh install the following error occurs:

```
> red-gql -c src/server.config.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/rodebert/Sites/spring/red-aggregation-layer/node_modules/apollo-env/lib/polyfills/array.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

See: 

- https://github.com/apollographql/apollo-server/issues/2263
- https://github.com/apollographql/apollo-tooling/issues/962 

for further information.

I think updating the version of `apollo-server-express` to 2.3.3 should fix this.

**Comment by mkai** [comment]
_apollo-server-express_ is now at 2.4.0 so I assume this can be closed. Please reopen if needed.
